from app.db.models.base import (
    Base, TimestampMixin, Column, UUID, BigInteger, Text, String,
    ForeignKey, relationship, uuid
)


class ChatRoom(Base, TimestampMixin):
    __tablename__ = "chat_room"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Relationships
    chat_logs = relationship("ChatLog", back_populates="chat_room")
    teams = relationship("Team", back_populates="chat_room")


class ChatLog(Base, TimestampMixin):
    __tablename__ = "chat_log"

    id = Column(
        BigInteger, primary_key=True, index=True
    )  # Identity generated by default
    chat_room_id = Column(
        UUID(as_uuid=True), ForeignKey("chat_room.id"), nullable=False
    )
    content = Column(Text, nullable=False)
    user_name = Column(String(255), nullable=False)

    # Relationships
    chat_room = relationship("ChatRoom", back_populates="chat_logs")
