pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install & Build') {
            steps {
                dir('ProjecTree-web') {
                    sh '''
                        docker run --rm -v $(pwd):/app -w /app node:24-alpine sh -c "npm install -g pnpm && pnpm install && pnpm build"
                    '''
                }
            }
        }

        stage('Docker Build') {
            when {
                branch 'fe-dev'
            }
            steps {
                dir('ProjecTree-web') {
                    sh 'docker build -t projectree-web .'
                }
            }
        }

        stage('Deploy') {
            when {
                branch 'fe-dev'
            }
            steps {
                sh '''
                    docker stop projectree-web || true
                    docker rm projectree-web || true
                    docker run -d --name projectree-web -p 3000:80 projectree-web
                '''
            }
        }
    }
}