pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install & Build') {
            agent {
                docker {
                    image 'node:24-alpine'
                    args '-v /var/jenkins_home/workspace:/var/jenkins_home/workspace'
                }
            }
            steps {
                dir('ProjecTree-web') {
                    sh 'npm install -g pnpm'
                    sh 'pnpm install'
                    sh 'pnpm build'
                }
            }
        }

        stage('Docker Build') {
            when {
                branch 'fe-dev'
            }
            steps {
                dir('ProjecTree-web') {
                    sh 'docker build -t projectree-web .'
                }
            }
        }

        stage('Deploy') {
            when {
                branch 'fe-dev'
            }
            steps {
                sh '''
                    docker stop projectree-web || true
                    docker rm projectree-web || true
                    docker run -d --name projectree-web -p 3000:80 projectree-web
                '''
            }
        }
    }
}