from sqlalchemy import (
    Boolean,
    Column,
    ForeignKey,
    Integer,
    String,
    Text,
    BigInteger,
    TIMESTAMP,
    Constraint,
    PrimaryKeyConstraint,
    Table,
    Enum,
    Identity,
)
from sqlalchemy.orm import relationship, Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID, ARRAY
from sqlalchemy.sql import func
import uuid

from app.db.base_class import Base, TimestampMixin
from app.agents.enums import NodeType, TaskType

# ----------------------------------------------------------------------
# Enums
# ----------------------------------------------------------------------
# Defined implicitly in schema checks, mapping them here if needed manually or just using String with validation
# Schema checks:
# member.oauth_provider: 'GOOGLE', 'GITHUB'
# node.priority: 'P0', 'P1', 'P2'
# node.status: 'TODO', 'IN_PROGRESS', 'DONE'
# task_node.type: 'BE', 'FE'


# ----------------------------------------------------------------------
# Chat
# ----------------------------------------------------------------------
class ChatRoom(Base, TimestampMixin):
    __tablename__ = "chat_room"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Relationships
    chat_logs = relationship("ChatLog", back_populates="chat_room")
    teams = relationship("Team", back_populates="chat_room")


class ChatLog(Base, TimestampMixin):
    __tablename__ = "chat_log"

    id = Column(
        BigInteger, primary_key=True, index=True
    )  # Identity generated by default
    chat_room_id = Column(
        UUID(as_uuid=True), ForeignKey("chat_room.id"), nullable=False
    )
    content = Column(Text, nullable=False)
    user_name = Column(String(255), nullable=False)

    # Relationships
    chat_room = relationship("ChatRoom", back_populates="chat_logs")


# ----------------------------------------------------------------------
# File / Document
# ----------------------------------------------------------------------
class FileProperty(Base, TimestampMixin):
    __tablename__ = "file_property"

    id = Column(BigInteger, primary_key=True)
    size = Column(BigInteger, nullable=False)
    uploader_id = Column(
        BigInteger, nullable=True
    )  # Assuming references member.id but no FK constraint in schema?
    content_type = Column(String(255))
    origin_file_name = Column(String(255))
    path = Column(String(255))
    saved_file_name = Column(String(255))

    # Join Inheritance or One-to-One?
    # document_property references file_property.id as PK + FK
    document_property = relationship(
        "DocumentProperty", uselist=False, back_populates="file_property"
    )


class DocumentProperty(Base):
    __tablename__ = "document_property"

    id = Column(BigInteger, ForeignKey("file_property.id"), primary_key=True)
    workspace_id = Column(BigInteger, ForeignKey("workspace.id"), nullable=False)

    # Relationships
    file_property = relationship("FileProperty", back_populates="document_property")
    workspace = relationship("Workspace", back_populates="documents")


# ----------------------------------------------------------------------
# Member / Team
# ----------------------------------------------------------------------
class Member(Base, TimestampMixin):
    __tablename__ = "member"

    id = Column(BigInteger, primary_key=True, index=True)
    email = Column(String(255))
    name = Column(String(255))
    nickname = Column(String(255))
    oauth_provider = Column(String(255))  # Check constraint: GOOGLE, GITHUB

    # Relationships
    teams = relationship("Team", back_populates="member")
    nodes = relationship(
        "Node", back_populates="owner"
    ) 


class Team(Base, TimestampMixin):
    __tablename__ = "team"

    id = Column(BigInteger, primary_key=True, index=True)
    member_id = Column(BigInteger, ForeignKey("member.id"), nullable=False)
    workspace_id = Column(BigInteger, ForeignKey("workspace.id"), nullable=False)
    chat_id = Column(UUID(as_uuid=True), ForeignKey("chat_room.id"), nullable=True)

    # Relationships
    member = relationship("Member", back_populates="teams")
    workspace = relationship("Workspace", back_populates="teams")
    chat_room = relationship("ChatRoom", back_populates="teams")


# ----------------------------------------------------------------------
# Workspace
# ----------------------------------------------------------------------
class Workspace(Base, TimestampMixin):
    __tablename__ = "workspace"

    id = Column(BigInteger, primary_key=True, index=True)
    name = Column(String(20), nullable=False)
    description = Column(Text)
    purpose = Column(String(20))
    domain = Column(String(20))
    identifier_prefix = Column(String(20))
    start_date = Column(
        TIMESTAMP(timezone=True)
    )  # timestamp(6) usually implies microsecond precision
    end_date = Column(TIMESTAMP(timezone=True))

    # Relationships
    documents = relationship("DocumentProperty", back_populates="workspace")
    teams = relationship("Team", back_populates="workspace")
    function_specifications = relationship(
        "FunctionSpecification", back_populates="workspace"
    )
    workspace_tech_stacks = relationship(
        "WorkspaceTechStack", back_populates="workspace"
    )


class FunctionSpecification(Base, TimestampMixin):
    __tablename__ = "function_specification"

    id = Column(BigInteger, primary_key=True, index=True)
    workspace_id = Column(BigInteger, ForeignKey("workspace.id"), nullable=False)
    name = Column(String(20))
    description = Column(Text)

    # Relationships
    workspace = relationship("Workspace", back_populates="function_specifications")


# ----------------------------------------------------------------------
# Tech Stack
# ----------------------------------------------------------------------
class TechVocabulary(Base, TimestampMixin):
    __tablename__ = "tech_vocabulary"

    id = Column(BigInteger, Identity(), primary_key=True, index=True)
    name = Column(String(100), nullable=False, unique=True)

    # Relationships
    # node_tech_stack and workspace_tech_stack reference this
    node_tech_stack = relationship(
        "NodeTechStack", back_populates="tech_vocabulary", uselist=False
    )
    workspace_tech_stack = relationship(
        "WorkspaceTechStack", back_populates="tech_vocabulary", uselist=False
    )


class TechStackInfo(Base, TimestampMixin):
    __tablename__ = "tech_stack_info"

    id = Column(BigInteger, Identity(), primary_key=True, index=True)
    is_selected = Column(Boolean, nullable=False)
    recommendation = Column(Integer, nullable=False)
    advantage = Column(Text)
    description = Column(Text)
    ref = Column(Text)
    disadvantage = Column(Text)

    # Relationships
    node_tech_stack = relationship(
        "NodeTechStack", back_populates="tech_stack_info", uselist=False
    )


class WorkspaceTechStack(Base, TimestampMixin):
    __tablename__ = "workspace_tech_stack"

    id = Column(BigInteger, Identity(), primary_key=True, index=True)
    tech_vocab_id = Column(
        BigInteger, ForeignKey("tech_vocabulary.id"), nullable=False, unique=True
    )
    workspace_id = Column(BigInteger, ForeignKey("workspace.id"), nullable=False)

    # Relationships
    tech_vocabulary = relationship(
        "TechVocabulary", back_populates="workspace_tech_stack"
    )
    workspace = relationship("Workspace", back_populates="workspace_tech_stacks")


class NodeTechStack(Base, TimestampMixin):
    __tablename__ = "node_tech_stack"

    id = Column(BigInteger, Identity(), primary_key=True, index=True)
    is_recommended = Column(Boolean, nullable=False)
    node_id = Column(BigInteger, ForeignKey("node.id"))
    tech_vocab_id = Column(BigInteger, ForeignKey("tech_vocabulary.id"))
    tech_stack_info_id = Column(
        BigInteger, ForeignKey("tech_stack_info.id"), unique=True
    )

    # Relationships
    node = relationship("Node", back_populates="tech_stacks")
    tech_vocabulary = relationship("TechVocabulary", back_populates="node_tech_stack")
    tech_stack_info = relationship("TechStackInfo", back_populates="node_tech_stack")


# ----------------------------------------------------------------------
# Node Hierarchy (Joined Table Inheritance)
# ----------------------------------------------------------------------
class Node(Base, TimestampMixin):
    __tablename__ = "node"

    id = Column(BigInteger, primary_key=True, index=True)
    member_id = Column(BigInteger, ForeignKey("member.id"))
    node_type = Column(Enum(NodeType), nullable=False)  # Discriminator
    identifier = Column(String(50))
    name = Column(String(30))
    description = Column(Text)
    note = Column(Text)
    priority = Column(String(255))  # P0, P1, P2
    status = Column(String(255))  # TODO, IN_PROGRESS, DONE

    __mapper_args__ = {
        "polymorphic_identity": "node",
        "polymorphic_on": node_type,
    }

    # Relationships
    owner = relationship("Member", back_populates="nodes")
    tech_stacks = relationship(
        "NodeTechStack", back_populates="node"
    )  
    ancestors = relationship(
        "Node",
        secondary="node_tree",
        primaryjoin="Node.id==node_tree.c.descendant_id",
        secondaryjoin="Node.id==node_tree.c.ancestor_id",
        backref="descendants",
        viewonly=True,  # Read-only for now to avoid complexity with association object if not needed
    )

    # Candidate relationship - One node can have many candidates? Or is it referencing a parent node?
    # Schema: candidate.node_id -> node.id (FK)
    candidates = relationship(
        "Candidate", foreign_keys="[Candidate.node_id]", back_populates="node"
    )

    # Derivation node relationship in Candidate
    # Schema: candidate.derivation_node_id -> node.id (FK)
    derived_candidates = relationship(
        "Candidate",
        foreign_keys="[Candidate.derivation_node_id]",
        back_populates="derivation_node",
    )


class AdvanceNode(Node):
    __tablename__ = "advance_node"

    node_id = Column(BigInteger, ForeignKey("node.id"), primary_key=True)
    difficult = Column(Integer)
    comparison = Column(Text)

    __mapper_args__ = {
        "polymorphic_identity": NodeType.ADVANCE,  # Guessing discriminator value
    }


class EpicNode(Node):
    __tablename__ = "epic_node"

    node_id = Column(BigInteger, ForeignKey("node.id"), primary_key=True)

    __mapper_args__ = {
        "polymorphic_identity": NodeType.EPIC,
    }


class ProjectNode(Node):
    __tablename__ = "project_node"

    node_id = Column(BigInteger, ForeignKey("node.id"), primary_key=True)

    __mapper_args__ = {
        "polymorphic_identity": NodeType.PROJECT,
    }


class StoryNode(Node):
    __tablename__ = "story_node"

    node_id = Column(BigInteger, ForeignKey("node.id"), primary_key=True)

    __mapper_args__ = {
        "polymorphic_identity": NodeType.STORY,
    }


from app.agents.enums import NodeType, TaskType

# ... (omitted code) ...

class TaskNode(Node):
    __tablename__ = "task_node"

    node_id = Column(BigInteger, ForeignKey("node.id"), primary_key=True)
    difficult = Column(Integer)
    comparison = Column(Text)
    type = Column(Enum(TaskType, values_callable=lambda x: [e.value for e in x], native_enum=False), nullable=True)  # BE, FE

    __mapper_args__ = {
        "polymorphic_identity": NodeType.TASK,
    }


# Association Table for Tree
node_tree = Table(
    "node_tree",
    Base.metadata,
    Column("ancestor_id", BigInteger, ForeignKey("node.id"), primary_key=True),
    Column("descendant_id", BigInteger, ForeignKey("node.id"), primary_key=True),
    Column("depth", Integer),
)


class Candidate(Base, TimestampMixin):
    __tablename__ = "candidate"

    id = Column(BigInteger, primary_key=True, index=True)
    node_id = Column(BigInteger, ForeignKey("node.id"), nullable=False)
    derivation_node_id = Column(BigInteger, ForeignKey("node.id"), unique=True)
    is_selected = Column(Boolean, nullable=False)
    name = Column(String(30))
    description = Column(Text)

    # Relationships
    node = relationship("Node", foreign_keys=[node_id], back_populates="candidates")
    derivation_node = relationship(
        "Node", foreign_keys=[derivation_node_id], back_populates="derived_candidates"
    )
