pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('ProjecTree-was') {
                    withCredentials([file(credentialsId: 'application-yml', variable: 'APP_YML')]) {
                        sh 'cp $APP_YML src/main/resources/application.yml'
                        sh 'chmod +x gradlew'
                        sh './gradlew build'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir('ProjecTree-was') {
                    sh './gradlew test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('ProjecTree-was') {
                    sh 'docker build -t projectree-was .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker stop projectree-was || true
                    docker rm projectree-was || true
                    docker run -d --name projectree-was --network app-network -p 8081:8080 projectree-was
                '''
            }
        }
    }
}